name: score-challenge

services:
  launcher:
    environment:
      CHALLENGE: score
      FLAG: "WCTF{x0r_l1n34r1ty_g0es_brrrr}"
    container_name: score
    image: score
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
