name: stakehouse-challenge

services:
  launcher:
    environment:
      CHALLENGE: stakehouse
      FLAG: "WCTF{st34k_w1th_a_s1d3_oF_r33ntR4nCy}"
    container_name: stakehouse
    image: stakehouse
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
