name: route-challenge

services:
  launcher:
    environment:
      CHALLENGE: route
      FLAG: "WCTF{r0ut35_t0_usd49_ebac07ea}"
    container_name: route
    image: route
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
