name: balance-proof-challenge

services:
  launcher:
    environment:
      CHALLENGE: balance-proof
      FLAG: "WCTF{P3c7r4Upgr4d3_4f92b1}"
    container_name: balance-proof
    image: balance-proof
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
