name: pigeon-challenge

services:
  launcher:
    environment:
      CHALLENGE: pigeon
      FLAG: "WCTF{P1G30N_P1G30N_DR34M_0F_P1G30N_0N3_P1G30N_TW0_5P1}"
    container_name: pigeon
    image: pigeon
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
