name: sentinel-protocol-challenge

services:
  launcher:
    environment:
      CHALLENGE: sentinel-protocol
      FLAG: "WCTF{s4m3_4ddr3ss_d1ff3r3nt_v1b3s}"
    container_name: sentinel-protocol
    image: sentinel-protocol
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
