name: uecallnft-challenge

services:
  launcher:
    environment:
      CHALLENGE: uecallnft
      FLAG: "WCTF{UNS4F3_S4F3_C4LL5}"
    container_name: uecallnft
    image: uecallnft
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
