name: red-memory-challenge

services:
  launcher:
    environment:
      CHALLENGE: red-memory
      FLAG: "WCTF{G07_GUD_5H4W_H3G4L3}"
    container_name: red-memory
    image: red-memory
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
