name: cheese-lending-challenge

services:
  launcher:
    environment:
      CHALLENGE: cheese-lending
      FLAG: "WCTF{l1qu1d_ch33s3_0r_r4c3tt3}"
    container_name: cheese-lending
    image: cheese-lending
    build: .
    command: socat TCP-LISTEN:1337,reuseaddr,fork EXEC:"python3 -u challenge.py",pty,stderr,setsid,sigint,sane
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network

networks:
  ctf_network:
    name: wonderlandctf
    external: true
