[workspace]
members = [
    "src/nr/flag_emitter",
    "src/nr/challenges/lucky_guess",
    "src/nr/challenges/summoners_deck",
    "src/nr/challenges/poisoned_flag",
    "src/nr/challenges/medium_flag_capture",
    "src/nr/challenges/the_observatory",
    "src/nr/test/external_revert_helper",
]
